fishing:
  fish-position:
    x: 979
    y: 572
    width: 2033
    height: 413
  fishing-progress:
    x: 1280
    y: 731
    width: 226
    height: 699
  key-binds:
    block: q
    recast: f
    drag-left: a
    drag-right: d
  timeouts:
    loop:
      min: 0.01
      max: 0.01
    notice-spam:
      min: 0.75
      max: 0.75
    reeling:
      min: 1.1
      max: 1.1
    reeling-pause:
      min: 1.5
      max: 1.5
    recast:
      min: 4.0
      max: 4.0
    cast:
      min: 0.1
      max: 0.3
colors:
  fish-track:
    r: 60
    g: 92
    b: 84
log_lvl: DEBUG
