fishing:
  fish-position:
    x: 979
    y: 572
    width: 3238
    height: 413
  fishing-progress:
    x: 1280
    y: 731
    width: 226
    height: 699
  key-binds:
    recast: f
  timeouts:
    recast:
      min: 1.0
      max: 4.0
colors:
  fish-track:
    r: 60
    g: 92
    b: 84
log_lvl: DEBUG
